discord:
  token: ""

data:
  server_type: "sqlite"
  database: "basset"
  host: "localhost"
  port: 3306
  user: "root"
  password: null

logging:
  use_color_output: true
  use_relative_output: true
  max_file_size_kb: 5000
  output_directory: "common/logs"
  date_time_format: "yyyy-MM-dd"